var a = 20;
var b;
b += a = 0;
console.log(b);
var x = "25";
var y = 25;
console.log(x == y);
console.log(x === y);
var z = 25;
console.log(x != z);
console.log(x !== z);
z = x / y;
console.log(z);
console.log("Conditional operator");
var s = a > z ? console.log("True") : console.log("False");
console.log(s);
var n = 5 > 10 ? "true" : 10 > 5 ? "true" : "nan";
console.log(n);
5 > 3 && console.log("True");
console.log(1.4 + 1.2 == 2.6);
