const str = "hello";
console.log(str.toUpperCase());
var str1 = str.toUpperCase();
console.log(str1);
console.log(str.charAt(2));
var str2 = "DIVYA";
console.log(str2.toLowerCase());
var s = "good mrng";
console.log(s.includes("mrng"));
console.log(s.replace("good", "Happy"));
console.log(s);
console.log(s.indexOf("o"));
console.log(s.concat("have a nyz day!"));
