let str = "Divya Arumugam from coimbatore";
let str1 = "   Hlo World!  ";
let str2 = new Object("Kavya");
console.log(str.concat(str1));
console.log(str.charAt(1));
console.log(str.endsWith("Arumugam"));
console.log(str.includes("Arumugam"));
console.log(str.indexOf("r"));
console.log(str.lastIndexOf("a"));
console.log(str.length);
console.log(str.match("Aru"));
console.log(str.matchAll("Arumugam"));
console.log(str.repeat(10));
console.log(str.replace("Divya", "Thiyagarajan"));
console.log(str.slice(0, 7));
console.log(str.split(" ", 3));
console.log(str.substring(0, 8));
console.log(str.toLowerCase());
console.log(str.toUpperCase());
console.log(str1.trim());
console.log(str2.valueOf());
console.log(str1.trimStart());
